import { Montserrat } from "next/font/google";
import "../app/styles/globals.scss";

const montserrat = Montserrat({ subsets: ["latin"] });



export const metadata = {
  title: "Rogue Dev Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
